permalink: /:year/:month/:day/:title.html
paginate: 10
#markdown: redcarpet
markdown: kramdown

# Author
author: 
  name: hubert
  email: hubert1002@sina.com
  link: http://hubert1002.github.io
  github: http://github.com/hubert1002

# Site
title: 我的代码人生
description: Blog of Hubert
url: http://hubert.github.io
rss_url: /pages/atom.xml

# gavatar Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics
ga:
  id: UA-54262064-1 
  url: hubert1002.github.io

# default active
active: 读书

# 首页除了最新文章外显示分类
# cates:
#   - Optimization
#   - LaTeX

# localization
locals:
  tags: 标签
  about: 关于
  newest: 吃饭睡觉打豆豆
  archive: 存档
